### ISSUE TITLE
Step policy Extra expenses and Debris removal factor default value should be 0

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/ODS_OpenExposureData#100]
We'd like to request that the default values for ExtraExpenseFactor and DebrisRemovalFactor be changed to 0 from 1, and values of 0 allowed please @MattDonovan82 .

The reason is that these factors are applied as an uplift factor to losses, and so they increase the loss for factors greater than 0. 

If there is no factor provided, i.e. blank field in the account file, then the value of 0 is the correct default. This is also the default we assign in the Oasis FM code so changing the OED spec will bring us in line.

FYI @sstruzik 
![image](https://user-images.githubusercontent.com/11421733/203554222-bda974ca-96ed-4462-a51c-d283736a85a2.png)
![image](https://user-images.githubusercontent.com/11421733/203554238-e5bae4c6-b49f-4b2e-a661-57e662a36d24.png)

**Comment by MattDonovan82** [comment]
so just the two defaults to be changed @johcarter @sstruzik?

We will look to get this included into OED v3.0.0 in Jan 2023 so please add anymore requests if necessary.

**Comment by sstruzik** [comment]
here is the list of change I'm proposing to put OED schema.

### for ExtraExpenseFactor and DebrisRemovalFactor, change default from 1 to 0 and remove max (was 1)
in practice in OasisLMF a factor of x mean that the loss will be multiply by 1+x.
So for a loss l is you want no ExtraExpenseFactor you need to set it to 0,
We also considered that there was no reason for those factor to be capped to 1, clearing debris after a catastrophe can cost much more than the value of a building (ex: Chernobyl power plant)

### RiskLevel: set default to SEL
this is the behavior coded in oasislmf

### NumberOfBuildings set min from 1 to 0
new meaning, 0 is for unknown number of buildings

**Comment by MattDonovan82** [comment]
for clarity, are you suggesting the default for NumberOfBuildings should be 0?

**Comment by MattDonovan82** [comment]
Closed as included in OED v3.0.0

**Comment by aiste-kalinauskaite** [comment]
Descriptions and valid value ranges no longer match up and contradict each other. If you want to keep the change of valid value range to go above 1, then the descriptions need to be updated (specifically this bit to be removed: "and must be a value >0 and ≤1").

**Comment by MattDonovan82** [comment]
@aiste-kalinauskaite I can include the following comment in the description for NumberofBuildings "Default to 1 but user should enter '0' if unknown".

However, I'm not sure I understand your comment above regarding the ExtraExpenseFactor and DebrisRemovalFactor which currently state "must be a value >0. For example, 0.12 for 12%."

Where is it mentioned "and must be a value >0 and ≤1" ?

**Comment by aiste-kalinauskaite** [comment]
@johcarter , @MattDonovan82 I have reviewed this against v3.0.0 when I raised the previous comment and it has been corrected in v3.1.0. So I will close it.
