### ISSUE TITLE
new account participation field in OED

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/ODS_OpenExposureData#109]
In order for OED to support account level terms, please could we add a field for account participation which represents a share of the loss across the entire account.

nb In the case of a single policy account, the existing LayerParticipation can be used to represent the account participation.

Account terms apply to the sum of policies where there are multiple policies. These could be multiple excess policies or the account could have multiple policy restrictions. 

An example of this is an account with two policies, A and B, where A is restricted to Locations 1-3 and B is restricted to Locations 4-6, where all of Locations 1-6 fall under the scope of the account.  In this case, policy losses are additive and the account share is applied to the sum of policy losses under the account.

Suggest the field name is AccParticipation with identical attributes to LayerParticipation.  Values between 0 and 1 inclusive and a default of 1 if empty/missing.

**Comment by MattDonovan82** [comment]
Thanks @johcarter. I'll add this to the spec for the v3 release notes.

**Comment by MattDonovan82** [comment]
Closed as duplicated here
https://github.com/OasisLMF/ODS_OpenExposureData/issues/122
