### ISSUE TITLE
Errors in OED v3.0.0 spec 

### ISSUE THREAD

**Issue by sambles** [OasisLMF/ODS_OpenExposureData#119]
The Following issues are causing [package build errors](https://github.com/OasisLMF/ODS_OpenExposureData/actions/runs/3882814932/jobs/6623394400) when extracting the OED spec into json for the **ods_tools** package. 
On branch [release/3.0.0](https://github.com/OasisLMF/ODS_OpenExposureData/tree/release/3.0.0)

* Loc Field `geom` has invalid DataType `string` ->  Updated to `varchar(250)` ?
* Loc Filed `NumberOfOccupants` exists in the OED input fields table twice 

![Screenshot from 2023-01-10 15-37-29](https://user-images.githubusercontent.com/9889973/211595036-dce24cd8-8f6a-410e-91d3-a9eb4f448877.png)

**Comment by MattDonovan82** [comment]
@sambles try this version
[OpenExposureData_Spec.xlsx](https://github.com/OasisLMF/ODS_OpenExposureData/files/10384535/OpenExposureData_Spec.xlsx)

**Comment by sambles** [comment]
Duplicate Construction code `7019`
![Screenshot from 2023-01-10 17-23-15](https://user-images.githubusercontent.com/9889973/211620023-8f22e604-2d35-4d68-aba2-cc8bf4ad573e.png)

**Comment by sambles** [comment]
Perils list needs blank rows to extract correctly (no idea why)
![Screenshot from 2023-01-10 17-12-43](https://user-images.githubusercontent.com/9889973/211620179-237f3483-d15f-4e65-a805-ff9f09d8a0e7.png)

**Comment by sambles** [comment]
I think we might need tests or better error handling to check for things like duplicate rows in the spec file.
