### ISSUE TITLE
Add AccParticipation to OED account

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/ODS_OpenExposureData#122]
## Description of Change
Add field AccParticipation to represent the share of loss at the account level for direct insurance

## Reasons for Change
Some complex policies have shares at the account level as well as at the policy level, and there is no current field to capture this. Oasis will support this as a financial term so we need to have it in the input data.

## Scope of change (which files do these apply to)
account

## Impact of change (are these breaking changes .. etc)
as this is a new field, validation tools for prior versions may reject the new field. Validation tools will need to be upgraded

## Data types, default values, are blanks allowed, list valid values

| **Field Name**    | **Data type** | **Default values** | **Blanks allowed** | **Valid values** |
|--------------------|----------------|---------------------|----------------------|-------------------|
| AccParticipation  |  float               |   1                         |        yes                   |  [0,1]                  |

**Comment by MattDonovan82** [comment]
@johcarter is this not the same issue as this:[
](https://github.com/OasisLMF/ODS_OpenExposureData/issues/109)

**Comment by MattDonovan82** [comment]
closed other issue (https://github.com/OasisLMF/ODS_OpenExposureData/issues/109)

**Comment by benhayes21** [comment]
released in OED 3.0.0
