### ISSUE TITLE
Occupancy is only property oriented (can we include motor?)

### ISSUE THREAD

**Issue by IPE-Pierre** [OasisLMF/ODS_OpenExposureData#129]
## Reasons for change
 
OccupancyCode are only covering property and not beyond... An Other 4000 category should be introduced to cover non property exposure

## Scope of change 
 
- [ ] Location File 
OccupancyCode dictionnary

## Impact of change
none in terms of code but massive in terms of model. Auto are somehow covered by constructionCode but implied massive duplication in terms of vulnerabilitydict redirection.

Occupancy should be rather master categories and constructioncode sub categories.

idea being 4000 for non property occupancy
4001 for Auto 4 wheels
4002 for 2 Wheelers
etc...

**Comment by MattDonovan82** [comment]
@IPE-Pierre As long as there are no duplications to existing occupancy codes and there is a demand for more 'non-property' classes, then these can be added in future, major releases.

Can you propose some codes and descriptions you would like to see added so the community can review them?

**Comment by IPE-Pierre** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

</head>

<body link="#0563C1" vlink="#954F72">



OED Code | Name | Description
-- | -- | --
1400 | Auto, unknow type & cover | Unknown Use, type and cover (MTPL / MOD)
1410 | Auto, Personal 4 Wheel unknown cover | Personal car 4-Wheel drive  unknown   cover (MTPL/MOD)
1411 | Auto, Personal 4 Wheel MOD | Personal car 4-Wheel drive own damage
1420 | Auto, Personal Moto unknown cover | Personal Moto 2-Wheel drive    unknown cover (MTPL/MOD)
1430 | Auto, Commercial / Utility | commercial utility car
1440 | Auto, Fleet 4 Wheel |  
1450 | Auto, Truck |  



</body>

</html>

**Comment by aiste-kalinauskaite** [comment]
There are a number of construction codes in OED spec already:
![image](https://github.com/OasisLMF/ODS_OpenExposureData/assets/42062835/1deac385-ec82-47c2-97a7-941fa057e355)

**Comment by johcarter** [comment]
From a modellers perspective, it is quite inconvenient to not have auto covered in occupancy codes.  It means you have to use both occupancy code and construction code to define vulnerability, and then you end up not supporting most combinations of these two codes.  

Perhaps we could consider moving auto codes out of construction and into occupancy?  I don't think they would be out of place, considering all the detailed infrastructure types OED now has in occupancy.  

Another option would be to identify an auto exposure by a single OccupancyCode so at least a distinct value can be entered rather than leaving it blank and defaulting to 1000 (unknown).

**Comment by MattDonovan82** [comment]
Including occupancy codes for motor would be a duplication as already present in construction and would be a major change and disruptive. As previously stated, the suggestion is to use a ew single occ code '1400' with the following description.

"Auto - general, to be used in conjunction with the relevant construction codes for auto (5850 - 5875)."

Thoughts? @IPE-Pierre

**Comment by IPE-Pierre** [comment]
The solution you are proposing is ok for me...

**Comment by MattDonovan82** [comment]
Updated as occ code 1260 (auto, general).
