### ISSUE TITLE
OED ESG metadata

### ISSUE THREAD

**Issue by IPE-Pierre** [OasisLMF/ODS_OpenExposureData#145]
OED are exposure capture but conceived toward CAT modeling for property. 

ESG is bringing much challenges essentially for reinsurers which should better capture their ESG exposure as well.

OED should embrace the movement and allow meta data for ESG purpose.

OASIS infrastuucture can easily encompass ESG therefore OED should allow ESG drivers designed by a specific workshop.

**Comment by johcarter** [comment]
What sort of fields are we talking about @IPE-Pierre ? could you provide more detail / examples please?

**Comment by MattDonovan82** [comment]
hi @IPE-Pierre can you suggest some fields for ESG?

**Comment by MattDonovan82** [comment]
Closing as no further progress.
