### ISSUE TITLE
Broken link to example data in documentation 

### ISSUE THREAD

**Issue by wforde-corelogic** [OasisLMF/ODS_OpenExposureData#149]
[Link ](https://github.com/OasisLMF/OEDtransform/tree/master/examples/cede_test)to example files on [this ](https://oasislmf.github.io/OpenDataTransform/components/setup/inputs.html#input-data)page is broken.

**Comment by MattDonovan82** [comment]
@benhayes21 looks like this link has been removed now?

**Comment by MattDonovan82** [comment]
@benhayes21 can this be closed as folder has been removed?

**Comment by MattDonovan82** [comment]
@ncerutti can we merge the tech documentation and ODS tools?

**Comment by ncerutti** [comment]
> @ncerutti can we merge the tech documentation and ODS tools?

Yes, I will update/replace the docs once the changes in ODS tools are finished.

**Comment by MattDonovan82** [comment]
hi @ncerutti can this now be closed?

**Comment by ncerutti** [comment]
hi @MattDonovan82 yes, OpenDataTransform's documentation is not relevant any more. I am copying the parts that are still useful into the main documentation
