### ISSUE TITLE
Add INSEE Code as a valid GeogScheme value

### ISSUE THREAD

**Issue by benhayes21** [OasisLMF/ODS_OpenExposureData#153]
## Description
INSEE code is the most granular definition of geography in France but is not supported by GADM. Some model providers use this in their definition of area, but it is not covered in the OED specification

## Reasons for change
FlexiLoc fields need to be used for INSEE but this is not ideal.

## Scope of change 
- [X] Location File 
- [ ] Accounts File 
- [ ] Reinsurance Scope 
- [ ] Reinsurance Info 

## Impact of change
Non-breaking

## Data type, default values, are blanks allowed, list valid values
New allowed value in `GeogScheme` of INSEE, no change to data types or rules

**Comment by MattDonovan82** [comment]
Seems like a reasonable request to include. We will leave this open for more comments but will be added to OED v4 when its released, unless any pushback?

**Comment by aiste-kalinauskaite** [comment]
Gegoscheme / GeogName fields are flexible. You could use any scheme you want, if you add X in front of it. This was designed to have the maximum flexibility for the users to be able to add and use whatever schemes they want. From Oasis loss generating perspective, it's just another field to aggregate the data into.
Of course, it can be added as a proper scheme in a future OED update. This was simply to indicate that there is no need to use FlexiLoc fields for this purpose.

**Comment by MattDonovan82** [comment]
We will add INSEE as a new supported Geogscheme to be a minor update for next minor release.
