### ISSUE TITLE
Motor TIV Documentation

### ISSUE THREAD

**Issue by benhayes21** [OasisLMF/ODS_OpenExposureData#155]
## Description
Can we create guidance on where TIV for motor should be stored in the location file? I suspect it's "OtherTIV" but it would be good to get clarity on this.

**Comment by aiste-kalinauskaite** [comment]
Yes, should be in OtherTIV.

**Comment by MattDonovan82** [comment]
Makes sense, maybe we should add this to the description for "otherTIV" in the spec to confirm it?

**Comment by aiste-kalinauskaite** [comment]
I believe it's already in the description: 
"Other Building Insured Value (primarily aimed at specific US policies). For motor exposures, use this field for TIV along with appropriate motor construction code."

**Comment by MattDonovan82** [comment]
Close as nothing more to add
