### ISSUE TITLE
RI Scope Required Fields to be updated

### ISSUE THREAD

**Issue by benhayes21** [OasisLMF/ODS_OpenExposureData#160]
## Description
The required and conditionally required fields for the RI Scope file in the OED files do not look to be correct/clear.

## Reasons for change
A number of fields in the RI Scope file are listed as "CR" but they should be optional.

## Scope of change 
- [ ] Location File 
- [ ] Accounts File 
- [X] Reinsurance Scope 
- [ ] Reinsurance Info 

## Impact of change
If users are ingesting the OED specification directly, then they will need to ensure that any data validation still works with the updated requirements

### OED Input Fields Tab - fields to be made optional
LocGroup | O
CedantName | O
ProducerName | O
LOB | O
ReinsTag | O
CededPercent | O

### OED CR Field Appendix Tab - changes to rules
ReinsScope | PortNumber | Required Field
-- | --
ReinsScope | AccNumber | CR6
ReinsScope | PolNumber | CR6-01
ReinsScope | LocGroup | To be removed
ReinsScope | LocNumber | CR6-01-1
ReinsScope | CedantName | To be removed
ReinsScope | ProducerName | To be removed
ReinsScope | LOB | To be removed
ReinsScope | CountryCode | To be removed
ReinsScope | ReinsTag | To be removed
ReinsScope | CededPercent | To be removed

**Comment by johcarter** [comment]
@benhayes21 before we implement this I have one small detail to check which is the required status of PortNumber. It is conditionally required if AccNumber, PolNumber, LocNumber is present, but otherwise can be left be blank.  Therefore, is it not just CR rather than R?

**Comment by johcarter** [comment]
So I would suggest: 

### OED CR Field Appendix Tab - changes to rules
ReinsScope | PortNumber | CR6
ReinsScope | AccNumber | CR6-01
ReinsScope | PolNumber | CR6-01-1
ReinsScope | LocGroup | To be removed
ReinsScope | LocNumber | CR6-01-2
ReinsScope | CedantName | To be removed
ReinsScope | ProducerName | To be removed
ReinsScope | LOB | To be removed
ReinsScope | CountryCode | To be removed
ReinsScope | ReinsTag | To be removed
ReinsScope | CededPercent | To be removed

**Comment by aiste-kalinauskaite** [comment]
@johcarter it is correct what you specified. The only issue I have with it, I don't quite know what benefit it would add. In fact, it would require some verbal explanations of how ReinsScope needs to be structured.

**Comment by johcarter** [comment]
This is just fixing a documentation bug @aiste-kalinauskaite. CR6 doesnt exist so most of the CR codes eg CR6-02 to CR6-07 don't make sense. it would help to clarify that the only dependence relationships in ri scope are LocNumber and PolNumber requiring AccNumber & PortNumber, and AccNumber requiring PortNumber
![image](https://github.com/OasisLMF/ODS_OpenExposureData/assets/11421733/33d37732-2b24-485a-99d6-c113d00ef5e9)

**Comment by johcarter** [comment]
Aiste, I understand now from your comments the CR codes were set this way to add information about how to structure the file.  We assumed it was a documentation error because CR6-02 to -07 are not technically dependent on any other field. I think simpler is better (ie make the suggested change), but I note that we lose some information and that we should add some explanatory documentation. I will check what we have already and make any clarifications.

**Comment by johcarter** [comment]
Have added a paragraph to documentation to explain optional versus CR filter fields, to go in with this change.

https://github.com/OasisLMF/ODS_OpenExposureData/blob/OED_v3.1_testing/OpenExposureData/3_OED_Import_Format.rst
