### ISSUE TITLE
Additional OccupancyCode values for commercial low/mid/high-rise blocks

### ISSUE THREAD

**Issue by stephenhutchingsjba** [OasisLMF/ODS_OpenExposureData#161]
## Description
This is a request for 3 additional OccupancyCode values, associated with the ‘Commercial’ Broad Category, for low/mid/high-rise apartment blocks.

## Reasons for change
This is to support specific exposure types which feel hard to represent effectively in OED at present. We’ve had several requests from clients to be able to model commercial policies covering an entire building, where the exact number of floors is not known.

For context, the problem is somewhat different for residential lines, as we find locations tend to be specified on an apartment-by-apartment basis, and an adequate approach exists: residential apartments may be represented using code 1055 and this can be used in combination with a FloorsOccupied to determine which vulnerability to apply given the floor number (e.g. a ground floor apartment and 10th floor behave very differently). Therefore this request only seeks a change for commercial lines.

## Scope of change 
 
- Location File (new valid values for OrgOccupancyCode and OccupancyCode fields)

## Impact of change
 
 
Extension to existing functionality. Would expect software using existing codes/files to continue to work.

However...@MattDonovan82 has told us "Any new codes will mean changes to the schema which from a technical standpoint could produce “breaking” changes - mainly for validation processes so they are considered major updates."

## Data type, default values, are blanks allowed, list valid values

| **Category** | **OED Code** | **AIR code** | **Name** | **Description** |**Code Range** |**Broad Category** |
|----------------|---------------|--------------------|--------------------|------------------|------------------|------------------|
|Occupancy|(tbd)|311?|Commercial,general,low-rise|As for General Commercial but where the building type is considered to be multiple-story low-rise and a value for FloorsOccupied may not be known.|1100-1149|Commercial|
|Occupancy|(tbd)|311?|Commercial,general,mid-rise|As for General Commercial but where the building type is considered to be multiple-story mid-rise and a value for FloorsOccupied may not be known.|1100-1149|Commercial|
|Occupancy|(tbd)|311?|Commercial,general,high-rise|As for General Commercial but where the building type is considered to be multiple-story high-rise and a value for FloorsOccupied may not be known.|1100-1149|Commercial|

**Comment by johcarter** [comment]
@stephenhutchingsjba I think there is some resistance to mixing up fields, ie NumberOfStoreys with OccupancyCode, but I understand that populating a guess into NumberOfStoreys when it is unknown is unsatisfactory.

Another suggestion is to introduce 3 special values into NumberOfStoreys as follows
-1 = Unknown NumberOfStoreys - low rise
-2 = Unknown NumberOfStoreys - mid rise
-3 = Unknown NumberOfStoreys - high rise

changing the valid value range from [0,) to [-3,) and entering descriptions into the 'Other values' for these special values.

This may break existing key service implementations that use NumberOfStoreys but all model developers have the option to map these values to the most appropriate vulnerability function as an enhancement to their logic for the extra information about height.

It could also be combined with other occupancy types where the number of storeys is unknown.

**Comment by MattDonovan82** [comment]
@johcarter this seems like a reasonable approach and more straightforward than proposing new occ codes.

What do yo think @aiste-kalinauskaite following our brief discussion on this a few weeks ago?

**Comment by philipoldham** [comment]
Agree that @johcarter's suggested approach would be preferable to adding additional Occupancy Codes.

**Comment by johcarter** [comment]
Thank you both. If there are no other opinions @MattDonovan82 I think this issue is ready for actioning with SC.

**Comment by MattDonovan82** [comment]
Yes. We will leave this open but implement into OED v4 which is due for release end of the year...........is that ok?

**Comment by stephenhutchingsjba** [comment]
Sounds good thanks. We're happy with the suggestion and pleased it'll be in OED v4.
