### ISSUE TITLE
Additional Occupancy code values for Commercial Banks and financial institutions

### ISSUE THREAD

**Issue by unnithan9** [OasisLMF/ODS_OpenExposureData#165]
## Description
This is a request for an additional Occupancy code value for financial institutions, including but not limiting to Retail Banks, Corporate or Commercial Banks, Investment Banks and Central Banks. 

## Reasons for change
For effective representation of specific exposure type that is challenging to convey in the current OED framework. We’ve had requests from clients to model banks and financial institutions where the business interruption functions are relatively different to other commercial occupancies.

## Scope of change 
Location File 

## Impact of change
Extension to existing functionality. 

## Data type, default values, are blanks allowed, list valid values

| **Category** | **OED Code (proposed)** | **Name** | **Description** | **OED code range** | **Broad Category** |
|----------------|---------------|---------------|--------------------|--------------------|------------------|
|      Occupancy          |   1125    |      Commercial, Banks               |      Occupancies involved in the financial industry. Including but not limiting to Retail Banks, Corporate or Commercial Banks, Investment Banks and Central Banks. These institutions may also give economic assistance such as: capital management, foreign exchange, Safe deposit boxes etc.              |      1100 - 1149            | Commercial|                |               |                    |                    |                  |

```[tasklist]
### Tasks
```

**Comment by MattDonovan82** [comment]
@unnithan9 no problem adding new codes if there is demand but we always try to avoid duplication. The only current code I can see that covers the financial industry is 1104 (Commercial, Professional,  technical and business). Reading your comment regarding more complexity around BI for banks, I assume the current 1104 would not suffice for this?

Any other comments from the community are welcome?

@johcarter @aiste-kalinauskaite @jones-matt

**Comment by unnithan9** [comment]
@MattDonovan82 : Thanks Matt. Yes, the complexity around BI requires a different code than 1104 for banks.

**Comment by aiste-kalinauskaite** [comment]
@MattDonovan82 generally, no issue in adding a new occupancy code when there is a need and the model vendors have vulnerability curves for this new information. I don't think OED is used for anything else other than modelling. So perhaps adding this when at least one model vendor has this in their vulnerability set would be a better option (rather than adding now).

**Comment by MattDonovan82** [comment]
new OED occ code for commercial, banks is 1125
