### ISSUE TITLE
Change default of 'SoilValue' from 0 to 'n/a'

### ISSUE THREAD

**Issue by michael-fehlmann** [OasisLMF/ODS_OpenExposureData#172]
## Description

According to the current [OED specs](https://github.com/OasisLMF/ODS_OpenExposureData/blob/develop/OpenExposureData/Docs/OpenExposureData_Spec.xlsx) the 'SoilValue' defaults to 0 which can be wrong information. For example, when the SoilValue refers to vs30 (m/s) (i.e. 'SoilType' is 1) the default value of 0 has an actual meaning (0 m/s) and can lead to wrong assumptions in the modelling further down the road. Thus the request is to change the default to 'n/a' instead.
 
## Reasons for change
 
In a Swiss Re Oasis model implementation, vulnerability curves are picked based on the vs30 'SoilValue', while assumptions are made in the code in case 'SoilValue' is 'n/a' (no information available) based on other information. With newer Oasis versions enforcing the OED default values, i.e. 'SoilValue' defaulting to 0, wrong vulnerability curves are picked.

## Scope of change 
 
- [x] Location File 
- [ ] Accounts File 
- [ ] Reinsurance Scope 
- [ ] Reinsurance Info 

## Data type, default values, are blanks allowed, list valid values
 

| **Field Name** | **Data type** | **Default values** | **Blanks allowed** | **Valid values** |
|----------------|---------------|--------------------|--------------------|------------------|
|SoilValue|float |**n/a** |YES|[0,)|

**Comment by MattDonovan82** [comment]
@michael-fehlmann this makes sense.

@johcarter @aiste-kalinauskaite would changing this have any implications elsewhere? Would using "N/A" have any data formatting issues?

**Comment by MattDonovan82** [comment]
We ok to use 'n/a' here @johcarter? @aiste-kalinauskaite ?

**Comment by johcarter** [comment]
This is the purpose of the SoilType field (0=no information, 1 = VS30 soil type), to differentiate between SoilValue=0 meaning no info and between meaning 0 m/s. @michael-fehlmann Could you read the value of SoilType into your model logic to map the SoilType,SoilValue value pair to the appropriate vuln curve?

**Comment by michael-fehlmann** [comment]
ok thanks @johcarter for this clarification, we just discussed this internally and your proposal works for our use case, i.e. for no information we will use SoilType=0 and SoilValue=0.

**Comment by johcarter** [comment]
No change needed as SoilType field can be used to differentiate between the two cases where SoilValue=0. Closing issue

**Comment by MattDonovan82** [comment]
I just added "and the corresponding unit" in the description of SoilValue just to be explicit. To clarify, a combination of 0,0 means no soil information but if there is soil information (i.e. 30 metres/second to shear wave velocity to 30m), it would be:

SoilType = 1 
SoilValue = 30

A value of 1 must be entered into SoilType when putting in a SoilValue.

**Comment by aiste-kalinauskaite** [comment]
In OED v3.2 data type for SoilType has been changed into float. There is no documentation about it nor has it been mentioned in the release notes. I think the change is unnecessary and SoilType should remain as tinyint (or any other integer type, in case there are more categories in the future).

**Comment by benhayes21** [comment]
changes to be reverted

**Comment by johcarter** [comment]
replaced by new issue #195 for clarity
