### ISSUE TITLE
Add new FTM1 GeogScheme to OpenExposureData_Spec.xlsx

### ISSUE THREAD

**Issue by RhiDaviesFathom** [OasisLMF/ODS_OpenExposureData#174]
## Description
Add a new to the "Other Values" sheet of the OpenExposureData_Spec.xlsx

## Reasons for change
Fathom now have their own GeoScheme called FTM1.

## Scope of change 
- [X] Location File 
- [ ] Accounts File 
- [ ] Reinsurance Scope 
- [ ] Reinsurance Info 

## Impact of change
This is an extension of the existing functionality to ensure the documentation is up to date.

## New row in the Other Values sheet
 

| **Category** | **Code** | **CodeDescription** | **Notes** | 
|----------------|---------------|--------------------|--------------------|
| GeogSheme |FTM1 |Urban areas |Used in Fathom model only |

**Comment by MattDonovan82** [comment]
HI @RhiDaviesFathom 
It would be preferred if this code for 'Urban Areas' could be published and open. I assume you are aiming to create some sort of .shp files under this? If so, could these be made open? We would prefer to keep things in OED as open and accessible to others as possible.

**Comment by MattDonovan82** [comment]
@RhiDaviesFathom ?

**Comment by jones-matt** [comment]
@MattDonovan82 we can discuss this, but I don't think this should block incorporation as there are plenty of other GeogSchemes in the OED spec which aren't 'open'. Can we change CodeDescription = "Urban Areas" to "Fathom admin boundaries" please? Thanks.

**Comment by MattDonovan82** [comment]
@jones-matt we can do this. We will add this to OED v3.2 in the next few weeks.

**Comment by MattDonovan82** [comment]
closed as implemented in v3.2.0
