### ISSUE TITLE
[Specification] Update how the OED specification is stored, move from excel to csv

### ISSUE THREAD

**Issue by sambles** [OasisLMF/ODS_OpenExposureData#192]
## Description
Its tricky to track changes to the specification via github because the main spec is stored as a single excel object. 
A better method would be to flip this around. 
* specification is stored in CSV format 
* on each commit the csv files are built into an excel file for review (by GitHub actions) 
* on each release an excel file is attached to that release as an asset. 
* automate release notes for OED spec changes 

--- 

#### To do 
* Link build artifact links with https://github.com/marocchino/sticky-pull-request-comment
* Attach both Excel and JSON to github release 
* Create release notes and changelog automatically from PR notes
*Automatically Link new OED versions (excel and json files) to Readme

**Comment by johcarter** [comment]
can hidden columns be removed in this change? eg SecMod? BackEndTableName etc in OED Input Fields

**Comment by johcarter** [comment]
yes to remove hidden columns

**Comment by johcarter** [comment]
@sambles  the gen excel part is ready for automation please.  I've specified the destination file as OpenExposureData/Docs/OpenExposureData.xlsx and not overwriting the old one OpenExposureData_spec.xls as I am still using this to make changes. But at some point we should discuss replacing the old spec with the generated one perhaps? thanks

**Comment by aiste-kalinauskaite** [comment]
@johcarter @sambles not a show stopper for OED v4 release, but for user usability (i.e. making it user friendly), how can one find the Excel spreadsheet? I've tried quite a few places in the directory (Tag = v4.0.0rc3), but I don't see where the Excel files sits.

**Comment by sambles** [comment]
Hi @aiste-kalinauskaite its build on each commit now, when a new change is made there should be **Build Preview** added to a pull request. 

The only drawback is these files expire over time.  So I've attached the most recent excel file to the bottom of 
https://github.com/OasisLMF/ODS_OpenExposureData/pull/209

**Comment by aiste-kalinauskaite** [comment]
@sambles is there a way to add this Excel file somewhere on GitHub so it can be accessed through there as oppose to the issue, like this one? From the users perspective it's difficult to have to remember the issue number so that it can be found at some point in the future.

**Comment by sambles** [comment]
@aiste-kalinauskaite, the plan is to attach the Excel file as an asset to a release when it goes live. You can see the release here: [Release 4.0.0rc3](https://github.com/OasisLMF/ODS_OpenExposureData/releases/tag/4.0.0rc3).

Are you suggesting we commit the file directly into the repository? 

I'd  prefer not to take that approach. The original reason for switching to CSVs and generating the Excel file was to improve the ability to track edits. Committing the Excel file would feel like a step backwards.

**Comment by aiste-kalinauskaite** [comment]
@sambles where it's currently placed is ok. My issue was that I couldn't find it. But now I can see how to navigate to the correct version, so that I can always find the older versions when needed. Thank you for your help.
