### ISSUE TITLE
[Property] ContentsFloodVuln updates introduced in v3.0.0

### ISSUE THREAD

**Issue by aiste-kalinauskaite** [OasisLMF/ODS_OpenExposureData#197]
## Description
ContentsFloodVuln was refactored in OED v3.0.0, yet not documented. No actual change is needed, only to highlight that it has been done.

## Reasons for change
To allign with other Vulnerability fields: BuildingFloodVuln and BIFloodVuln. 

## Scope of change 
- [x] Location File 
- [ ] Accounts File 
- [ ] Reinsurance Scope 
- [ ] Reinsurance Info 

## Impact of change
Affects only model vendors and clients that use this secondary modifier. However, for those that use it, the impact is major, as the descriptions for each code have changed and new codes are added.

## Data type, default values, are blanks allowed, list valid values
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/aiskal/AppData/Local/Temp/1/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/aiskal/AppData/Local/Temp/1/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink="#954F72">

Category | Code | CodeDescription
-- | -- | --
ContentsFloodVuln | 0 | Unknown
ContentsFloodVuln | 1 | No Susceptibility
ContentsFloodVuln | 2 | Very Low
ContentsFloodVuln | 3 | Low
ContentsFloodVuln | 4 | Moderate
ContentsFloodVuln | 5 | High
ContentsFloodVuln | 6 | Very High
ContentsFloodVuln | 7 | Total Susceptibility

</body>

</html>

**Comment by johcarter** [comment]
Note in release notes for 3.4 to say this changed in 3.0.0. No spec changed needed.
