### ISSUE TITLE
Repo restructure and tidy up

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/ODS_OpenExposureData#207]
## Description

- [ ] Move the specification to the root
- [ ] Move the docs into one folder
- [ ] Add list of links to all previous released versions of OED spec to the README and automatically update it with each new release
- [ ] Remove redundant directories / documentation

## Reasons for change
 

The folder structure is confusing and has multiple 'Docs' folders, so it is not intuitive to navigate.  The exposure class specifications are being integrated into one specification for v4 so the structure of the repo can be consolidated and simplified.

## Scope of change 
 
- [X] Specification
- [ ] Location File 
- [ ] Accounts File 
- [ ] Reinsurance Scope 
- [ ] Reinsurance Info 

## Impact of change
 
 

Specification will move location as well as format (excel-->csvs)

**Comment by aiste-kalinauskaite** [comment]
@johcarter @MattDonovan82 given that Cyber and Liability are going to be incorporated into OED v4.0.0, is there a need for Docs subfolders under each of those categories? 
<img width="140" alt="image" src="https://github.com/user-attachments/assets/14af818d-aacf-4298-9f0e-3a65191a2b74" />
I've looked under the Tag = v4.0.0rc3. Is that the right place for the final version?
