### ISSUE TITLE
Group Peril Codes

### ISSUE THREAD

**Issue by benhayes21** [OasisLMF/ODS_OpenExposureData#220]
## Description
Two issues with group peril codes
 - ZZ1 is not represented in the group peril to individual peril mappings
 -  the bitwise peril code for all perils has not been updated with the addition of sewage backup

## Reasons for change
missing ZZ1 code causes analyses to fail in oasislmf when the peril code is present

## Scope of change 
 
only change to peril mapping files in spec
- [ ] Location File 
- [ ] Accounts File 
- [ ] Reinsurance Scope 
- [ ] Reinsurance Info 

## Impact of change
non breaking - minor bug fix

**Comment by johcarter** [comment]
Also add missing PerilsCovered mappings for AA1 and VV1 for completeness
