### ISSUE TITLE
Describe OED fields relations and values dependencies/uniqueness

### ISSUE THREAD

**Issue by fl-ndaq** [OasisLMF/ODS_OpenExposureData#50]
A certain number of rules are not explicitely mentioned in the specifications, some appear to be checked during the keys lookup phase, eg:
* LocNumber are alphanumeric values that must be unique within an account, but not necessarily unique across multiple accounts
* ConNumber relation to PortNumber and AccNumber: see https://github.com/OasisLMF/OasisLMF/blob/480fcd2e7b61c79e3d852127b07bf989624f778b/oasislmf/preparation/il_inputs.py#L574
* Conditions/Policies: https://github.com/OasisLMF/OasisLMF/blob/1.15.14/oasislmf/preparation/il_inputs.py#L729
** account file combination (PortNumber + AccNumber + CondPriority) needs to be unique
** location file combination (PortNumber, AccNumber, LocNumber) + CondNumber needs to be unique
** in location file, if multiple identical (PortNumber, AccNumber, LocNumber), CondNumber cannot be null
** missing conditions: https://github.com/OasisLMF/OasisLMF/blob/1.15.16/oasislmf/preparation/il_inputs.py#L799

Suggestion: list all the implicit rules (not onl the above), starting with the ones that are currently being tested in the keys lookup

**Comment by MattDonovan82** [comment]
can we review and discuss this @johcarter ?

**Comment by benhayes21** [comment]
Cross check with https://github.com/OasisLMF/OasisLMF/blob/main/docs/OED_validation_guidelines.md to see what's missing

**Comment by benhayes21** [comment]
@aiste-kalinauskaite - can you review that document (above) and see what's missing please?

**Comment by aiste-kalinauskaite** [comment]
References to  BackEndTableName should be removed from the documentation. I thought you were planning to remove irrelevant information from the OED spec. Otherwise looks fine, if this is the full list of checks that are being performed in the background before an analysis is run.
