### ISSUE TITLE
Removal of BuildingType field in OED

### ISSUE THREAD

**Issue by MattDonovan82** [OasisLMF/ODS_OpenExposureData#70]
This is linked to issue (https://github.com/OasisLMF/OpenDataStandards/issues/68) where its suggested that capturing the specific **BuildingType** should be included in the description of the occupancies rather than having a separate field. 

This would make the occupancy codes more succinct and specific, reduce any ambiguity and essentially make conversions to and from OED easier.

The current BuildingType field is optional and so removing it shouldn't pose much risk to current users, except for validation processes, so plenty of notice to users is required.

Please post comments/thoughts in this issue.

Thanks.

**Comment by jones-matt** [comment]
Model vendors and users may already be using the BuildingType field so I think deprecating it is a large enough change to OED to warrant Steering Group comment (even if only via email).

The number of occupancy codes added is less than the number of BuildingType codes so are we happy to lose the extra codes?

**Comment by MattDonovan82** [comment]
Good point @jones-matt. We will of course refer this to the SC as it would be a major change.

Following your comment on there being more building types - does it make sense to add these as new specific occ codes so all are covered with associated descriptions?

**Comment by jones-matt** [comment]
Thanks. I think we should probably keep BuildingType but remove the BuildingType codes that now cause duplication given the additional occupancies in 2.3.0. The remaining remaining type codes would act as a variant to the main building type specified in the OccupancyCode. So, for example, a detached 'dome' would be represented by OccupancyCode = 1070 and BuildingType = 11. BuildingType becomes more of a secondary modifier. Adding extra occupancy codes for Earth house and Dome seems over the top to me.

**Comment by MattDonovan82** [comment]
See attached for proposed changes.
[Table - issue 70.xlsx](https://github.com/OasisLMF/OpenDataStandards/files/9505509/Table.-.issue.70.xlsx)

**Comment by MattDonovan82** [comment]
Closed as included in OED v3.0.0
