### ISSUE TITLE
Extending the length of LocUserDefx fields in Loc file

### ISSUE THREAD

**Issue by michael-fehlmann** [OasisLMF/ODS_OpenExposureData#77]
In the current OED specification, LocUserDef1, ..., LocUserDef5 in the Loc file are defined as varchar(20). For our integration, we are using these fields to pass some internal codes. We are planning to use some UIDs which exceed the 20 characters. Could this definition be altered to support longer strings, e.g. 100 or 200?

**Comment by MattDonovan82** [comment]
@michael-fehlmann no problem. This is just the length originally used in the SQL databases for data reporting purposes, no issues at all to increase them.

**Comment by MattDonovan82** [comment]
this will be extended to 100 characters.
