### ISSUE TITLE
Add an OED peril code for "off-floodplain" (OFP)

### ISSUE THREAD

**Issue by MattDonovan82** [OasisLMF/ODS_OpenExposureData#78]
There has been a request for this additional peril code so exposure/losses can be split by it. Is this a specific insurance coverage or just a component of a flood model?

Do other flood model vendors and/or users require this?

**Comment by MattDonovan82** [comment]
@OasisLMF/fathom @OasisLMF/jbadevteam

**Comment by oejwing** [comment]
My experience is that this is a deeply unhelpful term, perpetuating the idea that flood losses should only occur next to big rivers ("on-floodplain"). As vendors we certainly don't require it, and indeed would rather it did not become a peril code.

**Comment by stephenhutchingsjba** [comment]
JBA's starting position is similar for the reasons Ollie gives, and it's not a concept we use. In terms of purity of data design it also feels far in concept from the notion of a valid peril code.

Before dismissing completely it might help to understand the intended purpose behind the request; why would one want to split exposure or losses this way?

**Comment by siobhancampbell** [comment]
The request for off-flood-plain is driven by a policy wording, as in several geographies a different insurance products exists for “typical inundation” and “inundation of basement/lower stories mainly through a sewage water-backup”. An example of such could be the flood SBU (Sewer BackUp) policies in Canada (http://assets.ibc.ca/Documents/Resources/A-Primer-on-Severe-Weather-in-Canada.pdf, explained on the page 8), where such products often exist separately without other types of inundation. Their presence is sub-stational and absence of such model feature/support yields to limited model use for RI protection definition as well as for location level underwriting/accumulation.

(on behalf of Petr Puncochar, IF global flood head)

**Comment by MattDonovan82** [comment]
Considering the previous comments and for it to cover the sewage backup coverage, would it be better to label this as a separate peril code (maybe labelled "SEB" or such like?) rather than grouping it under flood? Calling it "off-floodplain" could be slightly misleading as it sounds like a model specific component rather than an insurance coverage.

**Comment by martinkuca1** [comment]
Hi Matt,
we went over that topic in IF again and as a result, SBU as stand-alone category doesn't fully represent what does our "off-flood plain" losses stand for (as it can be triggered on larger scale solely by inundated rivers), would make more sense to add it as i.e. "Other flood losses" under flood perils, or add as another peril on top of adding SBU. 
Peril code could be i.e. "OFL", but feel free to suggest different.


thanks
Martin

**Comment by MattDonovan82** [comment]
Closed as included in OED v3.0.0
