### ISSUE TITLE
Add new OED Loc fields related to vulnerability: VulnerabilityId, BuildingFloodVuln and BIFloodVuln

### ISSUE THREAD

**Issue by jones-matt** [OasisLMF/ODS_OpenExposureData#79]
Request to add three new fields **VulnerabilityID**, **BuildingFloodVuln** and **BIFloodVuln**, to the OED Loc file schema, and two new values for an existing field: **ContentsFloodVuln**.

**VulnerabilityID** allows a user to pass an integer that can be linked to a location-specific set of vulnerability functions. Either for information / reporting purposes or to link to a bespoke vulnerability implementation.

**BuildingFloodVuln** and **BIFloodVuln** added to mirror the existing **ContentsFloodVuln** field to allow the user to select flood vulnerability variations for a specific location for the Buildings and BI coverages.

Suggest adding two new values to **ContentsFloodVuln** to extend the range of options for this field. 'Very Low' to balance the range of options around the centre value and 'Total susceptibility' to help the user sensitivity test extreme vulnerability variations.

The codes in ContentsFloodVuln could logically be re-ordered (see my comment in the spreadsheet) - but this would be a breaking change so would need SG approval.

[OED new vulnerability field change request.xlsx](https://github.com/OasisLMF/OpenDataStandards/files/9235477/OED.new.vulnerability.field.change.request.xlsx)

**Comment by MattDonovan82** [comment]
@jones-matt this makes sense. We will leave this open to allow others to comment but will be implemented into ODS v3.0.0. The v3 release candidate will be available on the develop branch on (or around) 1st Sept - full release will be 3 months later (as per the ODS governance) to allow for community UAT.

**Comment by benhayes21** [comment]
@jones-matt would it make sense to call the `VulnerabilityID` field something different (maybe `VulnerabilitySetID`?) to differentiate it from the actual VulnerabilityIDs in a model?

**Comment by jones-matt** [comment]
Good point @benhayes21  - yes that makes sense.

**Comment by MattDonovan82** [comment]
Closed as included in OED v3.0.0
