### ISSUE TITLE
Additional currency fields in OED to support currency conversion

### ISSUE THREAD

**Issue by MattDonovan82** [OasisLMF/ODS_OpenExposureData#85]
Linked to this new feature in OasisLMF (https://github.com/OasisLMF/OasisLMF/issues/1081)

Additional OED fields in the Acc, Loc & ReinsScope files:

* OriginalCurrency - Currency in which the contract has been signed before any conversions
* RateOfExchange - Rate used to convert the terms from OriginalCurrency

**Comment by MattDonovan82** [comment]
Closed as included in OED v3.0.0

**Comment by aiste-kalinauskaite** [comment]
Description states that it's been added in "acc, loc and ReinsScope" fields. If I look at the OED v3 spec, it says that it's been added in all 4 files. However, I think that having the fields in ReinsScope file is unnecessary as there are no values that need any currency conversion. The only value field CededPercent  (the only field that isn't a filtering field) used for Surplus Treaties only can have percentages in there only ([0,1]). So there is nothing to convert.

**Comment by MattDonovan82** [comment]
@aiste-kalinauskaite yes I think I agree. Removing these would be a major change though so would be in OED v4.

@johcarter any further comments?

**Comment by johcarter** [comment]
@MattDonovan82 agree it should go into OED v4

**Comment by johcarter** [comment]
closing as a duplicate of #162
